import './globals.css'
import {NavBar} from "./Components/Componentsindex"
import {Footer}  from  './Components/Componentsindex'
// import NavBar from "./../../"
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <NavBar/>
        {children}
        <Footer/>
        </body>
    </html>
  )
}
