import './globals.css'
import {NavBar} from "./Components/Componentsindex"
import {Footer}  from  './Components/Componentsindex'
import {NFTMarketplaceProvider} from "../Context/NFTMarketplaceContext"
// import NavBar from "./../../"
export const metadata = {
  title: 'NFT BAZAR',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body>
        <NFTMarketplaceProvider>
        <NavBar/>
        {children}
        <Footer/>
        </NFTMarketplaceProvider>
        </body>
    </html>
  )
}
